apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exemple
  template:
    metadata:
      labels:
        app: exemple
    spec:
      containers:
        - name: exemple
          image: 23153122e351/exempletest
          ports:
            - containerPort: 8080